project:
  type: website

resources:
  - videos/   
  
website:
  title: "Fan Peng | Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: skills.qmd
        text: "Skills"
      - href: projects.qmd
        text: "Projects"
      - href: experiences.qmd
        text: "Internships"
      - href: about.qmd
        text: "About"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-float: true   # 想浮动时再加
    toc-location: right
    include-before-body: profile.html
    include-after-body: music.html




